import '../../data/models/adventure_level.dart';

class AdventureCatalog {
  AdventureCatalog._();

  static const List<String> worldNames = <String>[
    'Kristal Vadisi',
    'Buz Mağarası',
    'Ulduz Zirvəsi',
  ];

  static List<AdventureLevel> get all => _levels;

  static AdventureLevel? byId(int id) {
    for (final lvl in _levels) {
      if (lvl.id == id) return lvl;
    }
    return null;
  }

  static List<AdventureLevel> inWorld(int world) {
    return _levels.where((l) => l.world == world).toList(growable: false);
  }

  static int get worldCount => worldNames.length;

  static int get levelCount => _levels.length;

  static final List<AdventureLevel> _levels = <AdventureLevel>[
    // === Dünya 1: Kristal Vadisi ===
    const AdventureLevel(
      id: 1,
      world: 1,
      indexInWorld: 1,
      name: 'Başlanğıc',
      objective: LevelObjective(
        type: ObjectiveType.clearLines,
        target: 2,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 2,
      world: 1,
      indexInWorld: 2,
      name: 'İlk Addım',
      objective: LevelObjective(
        type: ObjectiveType.clearLines,
        target: 3,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 3,
      world: 1,
      indexInWorld: 3,
      name: 'Buz Toxumu',
      objective: LevelObjective(
        type: ObjectiveType.breakIce,
        target: 2,
      ),
      initialIceCoords: <List<int>>[
        <int>[3, 3],
        <int>[3, 4],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 4,
      world: 1,
      indexInWorld: 4,
      name: 'Genişlənmə',
      objective: LevelObjective(
        type: ObjectiveType.clearLines,
        target: 4,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 5,
      world: 1,
      indexInWorld: 5,
      name: 'Buz Kəsən',
      objective: LevelObjective(
        type: ObjectiveType.breakIce,
        target: 4,
      ),
      initialIceCoords: <List<int>>[
        <int>[2, 2],
        <int>[2, 3],
        <int>[5, 4],
        <int>[5, 5],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 6,
      world: 1,
      indexInWorld: 6,
      name: 'Xal Yığını',
      objective: LevelObjective(
        type: ObjectiveType.reachScore,
        target: 500,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 7,
      world: 1,
      indexInWorld: 7,
      name: 'Daha Sürətli',
      objective: LevelObjective(
        type: ObjectiveType.clearLines,
        target: 6,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 8,
      world: 1,
      indexInWorld: 8,
      name: 'Buz Gölü',
      objective: LevelObjective(
        type: ObjectiveType.breakIce,
        target: 6,
      ),
      initialIceCoords: <List<int>>[
        <int>[3, 3],
        <int>[3, 4],
        <int>[4, 3],
        <int>[4, 4],
        <int>[2, 3],
        <int>[5, 4],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 9,
      world: 1,
      indexInWorld: 9,
      name: 'Böyük Çağırış',
      objective: LevelObjective(
        type: ObjectiveType.reachScore,
        target: 800,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[
        <int>[0, 0],
        <int>[0, 7],
        <int>[7, 0],
        <int>[7, 7],
      ],
    ),
    const AdventureLevel(
      id: 10,
      world: 1,
      indexInWorld: 10,
      name: 'Vadinin Hökmdarı',
      objective: LevelObjective(
        type: ObjectiveType.clearLines,
        target: 10,
      ),
      initialIceCoords: <List<int>>[
        <int>[3, 3],
        <int>[3, 4],
        <int>[4, 3],
        <int>[4, 4],
      ],
      initialFillCoords: <List<int>>[],
    ),

    // === Dünya 2: Buz Mağarası ===
    const AdventureLevel(
      id: 11,
      world: 2,
      indexInWorld: 1,
      name: 'Soyuq Giriş',
      objective: LevelObjective(
        type: ObjectiveType.breakIce,
        target: 6,
      ),
      initialIceCoords: <List<int>>[
        <int>[2, 2],
        <int>[2, 5],
        <int>[5, 2],
        <int>[5, 5],
        <int>[3, 3],
        <int>[4, 4],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 12,
      world: 2,
      indexInWorld: 2,
      name: 'Buz Sütunları',
      objective: LevelObjective(
        type: ObjectiveType.breakIce,
        target: 8,
      ),
      initialIceCoords: <List<int>>[
        <int>[1, 1],
        <int>[2, 1],
        <int>[3, 1],
        <int>[5, 6],
        <int>[6, 6],
        <int>[7, 6],
        <int>[1, 6],
        <int>[7, 1],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 13,
      world: 2,
      indexInWorld: 3,
      name: 'Kəskin Xal',
      objective: LevelObjective(
        type: ObjectiveType.reachScore,
        target: 1200,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 14,
      world: 2,
      indexInWorld: 4,
      name: 'Buz Divarı',
      objective: LevelObjective(
        type: ObjectiveType.breakIce,
        target: 10,
      ),
      initialIceCoords: <List<int>>[
        <int>[3, 2],
        <int>[3, 3],
        <int>[3, 4],
        <int>[3, 5],
        <int>[4, 2],
        <int>[4, 3],
        <int>[4, 4],
        <int>[4, 5],
        <int>[3, 1],
        <int>[4, 6],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 15,
      world: 2,
      indexInWorld: 5,
      name: 'Dondurucu',
      objective: LevelObjective(
        type: ObjectiveType.clearLines,
        target: 12,
      ),
      initialIceCoords: <List<int>>[
        <int>[0, 3],
        <int>[0, 4],
        <int>[7, 3],
        <int>[7, 4],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 16,
      world: 2,
      indexInWorld: 6,
      name: 'Sonsuz Soyuq',
      objective: LevelObjective(
        type: ObjectiveType.breakIce,
        target: 12,
      ),
      initialIceCoords: <List<int>>[
        <int>[2, 2],
        <int>[2, 3],
        <int>[2, 4],
        <int>[2, 5],
        <int>[5, 2],
        <int>[5, 3],
        <int>[5, 4],
        <int>[5, 5],
        <int>[3, 1],
        <int>[3, 6],
        <int>[4, 1],
        <int>[4, 6],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 17,
      world: 2,
      indexInWorld: 7,
      name: 'Buz Kristalı',
      objective: LevelObjective(
        type: ObjectiveType.reachScore,
        target: 1800,
      ),
      initialIceCoords: <List<int>>[
        <int>[3, 3],
        <int>[3, 4],
        <int>[4, 3],
        <int>[4, 4],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 18,
      world: 2,
      indexInWorld: 8,
      name: 'Dondurulmuş Zirvə',
      objective: LevelObjective(
        type: ObjectiveType.clearLines,
        target: 14,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[
        <int>[0, 0],
        <int>[0, 1],
        <int>[1, 0],
        <int>[6, 7],
        <int>[7, 6],
        <int>[7, 7],
      ],
    ),
    const AdventureLevel(
      id: 19,
      world: 2,
      indexInWorld: 9,
      name: 'Buz Fırtınası',
      objective: LevelObjective(
        type: ObjectiveType.breakIce,
        target: 14,
      ),
      initialIceCoords: <List<int>>[
        <int>[2, 3],
        <int>[2, 4],
        <int>[3, 2],
        <int>[3, 5],
        <int>[4, 2],
        <int>[4, 5],
        <int>[5, 3],
        <int>[5, 4],
        <int>[1, 3],
        <int>[1, 4],
        <int>[6, 3],
        <int>[6, 4],
        <int>[3, 3],
        <int>[4, 4],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 20,
      world: 2,
      indexInWorld: 10,
      name: 'Mağara Hökmdarı',
      objective: LevelObjective(
        type: ObjectiveType.reachScore,
        target: 2500,
      ),
      initialIceCoords: <List<int>>[
        <int>[3, 3],
        <int>[3, 4],
        <int>[4, 3],
        <int>[4, 4],
        <int>[2, 2],
        <int>[5, 5],
      ],
      initialFillCoords: <List<int>>[],
    ),

    // === Dünya 3: Ulduz Zirvəsi ===
    const AdventureLevel(
      id: 21,
      world: 3,
      indexInWorld: 1,
      name: 'Ulduz Qapısı',
      objective: LevelObjective(
        type: ObjectiveType.reachScore,
        target: 2000,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 22,
      world: 3,
      indexInWorld: 2,
      name: 'Parlaq Yol',
      objective: LevelObjective(
        type: ObjectiveType.clearLines,
        target: 16,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 23,
      world: 3,
      indexInWorld: 3,
      name: 'Kosmik Buz',
      objective: LevelObjective(
        type: ObjectiveType.breakIce,
        target: 16,
      ),
      initialIceCoords: <List<int>>[
        <int>[0, 0],
        <int>[0, 7],
        <int>[7, 0],
        <int>[7, 7],
        <int>[3, 3],
        <int>[3, 4],
        <int>[4, 3],
        <int>[4, 4],
        <int>[2, 2],
        <int>[2, 5],
        <int>[5, 2],
        <int>[5, 5],
        <int>[1, 3],
        <int>[1, 4],
        <int>[6, 3],
        <int>[6, 4],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 24,
      world: 3,
      indexInWorld: 4,
      name: 'Böyük Ulduz',
      objective: LevelObjective(
        type: ObjectiveType.reachScore,
        target: 3000,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[
        <int>[3, 3],
        <int>[3, 4],
        <int>[4, 3],
        <int>[4, 4],
      ],
    ),
    const AdventureLevel(
      id: 25,
      world: 3,
      indexInWorld: 5,
      name: 'Sonsuz Döngə',
      objective: LevelObjective(
        type: ObjectiveType.clearLines,
        target: 20,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 26,
      world: 3,
      indexInWorld: 6,
      name: 'Buz Kraliçası',
      objective: LevelObjective(
        type: ObjectiveType.breakIce,
        target: 20,
      ),
      initialIceCoords: <List<int>>[
        <int>[2, 2],
        <int>[2, 3],
        <int>[2, 4],
        <int>[2, 5],
        <int>[3, 2],
        <int>[3, 5],
        <int>[4, 2],
        <int>[4, 5],
        <int>[5, 2],
        <int>[5, 3],
        <int>[5, 4],
        <int>[5, 5],
        <int>[3, 3],
        <int>[3, 4],
        <int>[4, 3],
        <int>[4, 4],
        <int>[1, 3],
        <int>[1, 4],
        <int>[6, 3],
        <int>[6, 4],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 27,
      world: 3,
      indexInWorld: 7,
      name: 'Ulduz Fırtınası',
      objective: LevelObjective(
        type: ObjectiveType.reachScore,
        target: 4000,
      ),
      initialIceCoords: <List<int>>[],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 28,
      world: 3,
      indexInWorld: 8,
      name: 'Kainat Yolu',
      objective: LevelObjective(
        type: ObjectiveType.clearLines,
        target: 24,
      ),
      initialIceCoords: <List<int>>[
        <int>[3, 3],
        <int>[3, 4],
        <int>[4, 3],
        <int>[4, 4],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 29,
      world: 3,
      indexInWorld: 9,
      name: 'Buz Kainatı',
      objective: LevelObjective(
        type: ObjectiveType.breakIce,
        target: 24,
      ),
      initialIceCoords: <List<int>>[
        <int>[0, 0],
        <int>[0, 1],
        <int>[1, 0],
        <int>[0, 6],
        <int>[0, 7],
        <int>[1, 7],
        <int>[6, 0],
        <int>[7, 0],
        <int>[7, 1],
        <int>[6, 7],
        <int>[7, 6],
        <int>[7, 7],
        <int>[3, 3],
        <int>[3, 4],
        <int>[4, 3],
        <int>[4, 4],
        <int>[2, 2],
        <int>[2, 5],
        <int>[5, 2],
        <int>[5, 5],
        <int>[3, 2],
        <int>[4, 5],
        <int>[3, 5],
        <int>[4, 2],
      ],
      initialFillCoords: <List<int>>[],
    ),
    const AdventureLevel(
      id: 30,
      world: 3,
      indexInWorld: 10,
      name: 'Kristal Hökmdarı',
      objective: LevelObjective(
        type: ObjectiveType.reachScore,
        target: 5000,
      ),
      initialIceCoords: <List<int>>[
        <int>[3, 3],
        <int>[3, 4],
        <int>[4, 3],
        <int>[4, 4],
      ],
      initialFillCoords: <List<int>>[
        <int>[0, 0],
        <int>[0, 7],
        <int>[7, 0],
        <int>[7, 7],
      ],
    ),
  ];
}
